### PR TITLE
[Example && Src] Develop Pingpong example and fix some bugs

### LINKED ISSUE #10: [Example] PingpongClient often crashes
In `example/pingpong/pingpong_client*` ans `example/pingpong/client_main`.
When it runs, it will crash in a short time because of "core dump: segmentation default".
I tried to find the bug, and found that when a raw pointer is used by a lot of objects it will be inaccessible (I mean that memory space the pointer pointed to).
@macosunity @renph @L-Super @CosmosNing @maxlv7

### PR DESCRIPTION
**Pull request by Sigma711**
### Purpose

- Develop Pingpong example.
- Improve ChatRoom example.
- Fix bugs in source of taotu.

### Changes

- In `example/pingpong/`.
- In `example/chat_room/`.
- In `src/`.

### Review Instructions

- Read differences in the modules of source and the new examples (ChatRoom and Pingpong).
- But sometimes PingpongClient is not stable (it maybe causes "segmentation fault").

### CODE REVIEW

**Review by million-2002 — CHANGES_REQUESTED** [review]
(deleted)

**Review by million-2002 — CHANGES_REQUESTED** [review]
(deleted)

**Review by million-2002 — APPROVED** [review]
LGTM

**Comment by Sigma711** [comment]
> ???

**Pull request merged**
